//! Cute MIR/AST -> C++17 source emission.
//!
//! Codegen lowers directly from the syntactic AST to C++. HIR / type-check
//! layers fold in only when codegen actually needs disambiguation that
//! the AST cannot answer (e.g. nullable-of-QObject vs nullable-of-value).
//!
//! Each Cute module emits one `.h` + one `.cpp` pair. QObject-derived
//! classes get the moc-replacement section (string table + qt_meta_data
//! array + staticMetaObject + qt_metacall family) generated by `cute-meta`
//! and stitched in by this crate.

pub mod cpp;
pub mod desugar_state;
pub mod desugar_store;
pub mod desugar_suite;
pub mod mangle;
pub mod qss;
pub mod style;
pub mod ty;

pub use cpp::{CodegenTypeInfo, EmitError, EmitResult, QmlImport, emit_module};
