// Cute runtime: Result<T, E> for the `!T` error-union surface.
//
// Spec: error union return types `!T`, `?` operator for propagation, `case
// when ok(v) / err(e)` for matching. This header provides the C++20
// representation that codegen targets.
//
// The interface intentionally mirrors what cute-lower needs to emit:
// - `Result<T,E>::ok(v)` / `Result<T,E>::err(e)` constructors.
// - `is_ok()` / `is_err()` discriminators (for `case` arm dispatch).
// - `unwrap()` / `unwrap_err()` for arm bodies.
// - `void` specialization so `fn foo() !void` lowers cleanly.
//
// We use std::variant with a leading std::monostate slot so that a default-
// constructed Result is in a "neither ok nor err" state - useful for early
// returns generated by the `?` operator before assignment.

#pragma once

#include <compare>
#include <cstdint>
#include <stdexcept>
#include <type_traits>
#include <utility>
#include <variant>

// `QtBoolError` is the canonical err-side type for Qt methods that
// signalled failure via a `bool *ok = nullptr` out-parameter (e.g.
// `QString::toInt`, `QByteArray::toDouble`). The Cute side declares
// this enum in `stdlib/qt/qcore.qpi` for type-checking; the C++ side
// lives at file scope here so the `@lifted_bool_ok` codegen wrapper
// can name it without an include sweep. Mirrors the user-side
// codegen of `error E { failed }`: a class with a `static failed()`
// factory.
class QtBoolError {
public:
    enum class Tag : std::uint8_t { Failed };

    [[nodiscard]] static QtBoolError failed() noexcept { return QtBoolError(Tag::Failed); }

    Tag tag() const noexcept { return tag_; }
    bool is_failed() const noexcept { return tag_ == Tag::Failed; }

    friend auto operator<=>(const QtBoolError&, const QtBoolError&) = default;

private:
    explicit QtBoolError(Tag t) noexcept : tag_(t) {}
    Tag tag_;
};

namespace cute {

namespace detail {
struct VoidOk {
    friend auto operator<=>(const VoidOk&, const VoidOk&) = default;
};
}

template <typename T, typename E>
class Result {
public:
    Result() = default;

    [[nodiscard("ignoring this Result loses the error case")]]
    static Result ok(T value) {
        Result r;
        r.value_.template emplace<1>(std::move(value));
        return r;
    }

    [[nodiscard("ignoring this Result loses the error case")]]
    static Result err(E error) {
        Result r;
        r.value_.template emplace<2>(std::move(error));
        return r;
    }

    bool is_ok() const noexcept { return value_.index() == 1; }
    bool is_err() const noexcept { return value_.index() == 2; }

    // Defaulted three-way ordering. Kicks in when both `T` and `E` are
    // <=>-comparable; otherwise the comparison itself becomes ill-formed
    // (deleted) and Result is non-orderable for that pair, which matches
    // user expectations - you don't get to sort Results of incomparable
    // payloads. Lets `std::sort(vec_of_results)`, `std::set<Result<T,E>>`
    // and the like compose without hand-rolled adapters.
    friend auto operator<=>(const Result&, const Result&) = default;

    T& unwrap() & {
        if (!is_ok()) throw std::runtime_error("cute::Result::unwrap on err/empty");
        return std::get<1>(value_);
    }

    const T& unwrap() const & {
        if (!is_ok()) throw std::runtime_error("cute::Result::unwrap on err/empty");
        return std::get<1>(value_);
    }

    T unwrap() && {
        if (!is_ok()) throw std::runtime_error("cute::Result::unwrap on err/empty");
        return std::get<1>(std::move(value_));
    }

    E& unwrap_err() & {
        if (!is_err()) throw std::runtime_error("cute::Result::unwrap_err on ok/empty");
        return std::get<2>(value_);
    }

    E unwrap_err() && {
        if (!is_err()) throw std::runtime_error("cute::Result::unwrap_err on ok/empty");
        return std::get<2>(std::move(value_));
    }

private:
    std::variant<std::monostate, T, E> value_;
};

// Specialization for `!void`: ok() takes no value.
template <typename E>
class Result<void, E> {
public:
    Result() = default;

    [[nodiscard("ignoring this Result loses the error case")]]
    static Result ok() {
        Result r;
        r.value_.template emplace<1>(detail::VoidOk{});
        return r;
    }

    [[nodiscard("ignoring this Result loses the error case")]]
    static Result err(E error) {
        Result r;
        r.value_.template emplace<2>(std::move(error));
        return r;
    }

    bool is_ok() const noexcept { return value_.index() == 1; }
    bool is_err() const noexcept { return value_.index() == 2; }

    friend auto operator<=>(const Result&, const Result&) = default;

    void unwrap() const {
        if (!is_ok()) throw std::runtime_error("cute::Result<void>::unwrap on err/empty");
    }

    E& unwrap_err() & {
        if (!is_err()) throw std::runtime_error("cute::Result<void>::unwrap_err on ok/empty");
        return std::get<2>(value_);
    }

    E unwrap_err() && {
        if (!is_err()) throw std::runtime_error("cute::Result<void>::unwrap_err on ok/empty");
        return std::get<2>(std::move(value_));
    }

private:
    std::variant<std::monostate, detail::VoidOk, E> value_;
};

}  // namespace cute
